return {
  cap_path_format = 'timeflaps/tick%d/cap%05d.png',
  cap_resolution = { 1920, 1080 },
  cap_zoom = 0.45,
  cap_zoom_base_res_y = 720,
  cap_show_gui = false,
  cap_show_entity_info = true,
  cap_save = true,
  cap_autostart = false,
  cap_limit = 0,
  cap_force_daytime = false,
  target_speedup = 60,
  target_video_fps = 60,
  debug = false,
  cam_debug_pos = false,
  cam_follow_dead_radius = 2.5,
  cam_follow_smooth_factor = 5,
  cam_fixed_pos = nil,
}
